"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unified_python_sdk.models.shared import analyticssession as shared_analyticssession
from unified_python_sdk.types import BaseModel, UNSET_SENTINEL
from unified_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)


class GetAnalyticsSessionQueryParamFields(str, Enum):
    ID = "id"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    PROPERTY_ID = "property_id"
    VISITOR_ID = "visitor_id"
    START_AT = "start_at"
    END_AT = "end_at"
    DURATION_SECONDS = "duration_seconds"
    LANDING_PAGE = "landing_page"
    EXIT_PAGE = "exit_page"
    PAGE_VIEWS = "page_views"
    EVENTS_COUNT = "events_count"
    SOURCE = "source"
    MEDIUM = "medium"
    CAMPAIGN = "campaign"
    DEVICE = "device"
    BROWSER = "browser"
    OS = "os"
    COUNTRY = "country"
    CITY = "city"
    IS_BOUNCE = "is_bounce"
    IS_CONVERSION = "is_conversion"
    RAW = "raw"


class GetAnalyticsSessionRequestTypedDict(TypedDict):
    connection_id: str
    r"""ID of the connection"""
    id: str
    r"""ID of the Session"""
    fields: NotRequired[List[GetAnalyticsSessionQueryParamFields]]
    r"""Fields to return"""
    raw: NotRequired[str]
    r"""Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar"""


class GetAnalyticsSessionRequest(BaseModel):
    connection_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the connection"""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the Session"""

    fields: Annotated[
        Optional[List[GetAnalyticsSessionQueryParamFields]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Fields to return"""

    raw: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fields", "raw"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAnalyticsSessionResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    analytics_session: NotRequired[shared_analyticssession.AnalyticsSessionTypedDict]
    r"""Successful"""


class GetAnalyticsSessionResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    analytics_session: Optional[shared_analyticssession.AnalyticsSession] = None
    r"""Successful"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["AnalyticsSession"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
