"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unified_python_sdk.models.shared import messagingmessage as shared_messagingmessage
from unified_python_sdk.types import BaseModel, UNSET_SENTINEL
from unified_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)


class PatchMessagingMessageQueryParamFields(str, Enum):
    ID = "id"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    CHANNEL_ID = "channel_id"
    CHANNEL_IDS = "channel_ids"
    CHANNELS = "channels"
    PARENT_ID = "parent_id"
    PARENT_MESSAGE_ID = "parent_message_id"
    ROOT_MESSAGE_ID = "root_message_id"
    MESSAGE_THREAD_IDENTIFIER = "message_thread_identifier"
    AUTHOR_MEMBER = "author_member"
    DESTINATION_MEMBERS = "destination_members"
    HIDDEN_MEMBERS = "hidden_members"
    MENTIONED_MEMBERS = "mentioned_members"
    REACTIONS = "reactions"
    SUBJECT = "subject"
    MESSAGE = "message"
    MESSAGE_HTML = "message_html"
    MESSAGE_MARKDOWN = "message_markdown"
    ATTACHMENTS = "attachments"
    WEB_URL = "web_url"
    REFERENCE = "reference"
    HAS_CHILDREN = "has_children"
    IS_UNREAD = "is_unread"
    BUTTONS = "buttons"
    RAW = "raw"


class PatchMessagingMessageRequestTypedDict(TypedDict):
    messaging_message: shared_messagingmessage.MessagingMessageTypedDict
    connection_id: str
    r"""ID of the connection"""
    id: str
    r"""ID of the Message"""
    fields: NotRequired[List[PatchMessagingMessageQueryParamFields]]
    r"""Fields to return"""
    raw: NotRequired[str]
    r"""Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar"""


class PatchMessagingMessageRequest(BaseModel):
    messaging_message: Annotated[
        shared_messagingmessage.MessagingMessage,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    connection_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the connection"""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the Message"""

    fields: Annotated[
        Optional[List[PatchMessagingMessageQueryParamFields]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Fields to return"""

    raw: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fields", "raw"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PatchMessagingMessageResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    messaging_message: NotRequired[shared_messagingmessage.MessagingMessageTypedDict]
    r"""Successful"""


class PatchMessagingMessageResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    messaging_message: Optional[shared_messagingmessage.MessagingMessage] = None
    r"""Successful"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MessagingMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
