workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://api.unified.to/openapi.json
              authSecret: $openapi_doc_auth_token
targets:
    python-target:
        target: python
        source: my-source
        publish:
            pypi:
                token: $PYPI_TOKEN
