"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import crmdeal as shared_crmdeal
from typing import Optional



@dataclasses.dataclass
class PutCrmConnectionIDDealIDSecurity:
    jwt: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'authorization' }})
    




@dataclasses.dataclass
class PutCrmConnectionIDDealIDRequest:
    connection_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': False }})
    r"""ID of the connection"""
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""ID of the Deal"""
    crm_deal: Optional[shared_crmdeal.CrmDeal] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""A deal represents an opportunity with companies and/or contacts"""
    




@dataclasses.dataclass
class PutCrmConnectionIDDealIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    crm_deal: Optional[shared_crmdeal.CrmDeal] = dataclasses.field(default=None)
    r"""Successful"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

