"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .genaicontent import GenaiContent, GenaiContentTypedDict
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict
from unified_python_sdk.types import BaseModel, UNSET_SENTINEL


class GenaiPromptTypedDict(TypedDict):
    max_tokens: NotRequired[float]
    mcp_deferred_tools: NotRequired[List[str]]
    mcp_url: NotRequired[str]
    messages: NotRequired[List[GenaiContentTypedDict]]
    model_id: NotRequired[str]
    raw: NotRequired[Dict[str, Any]]
    responses: NotRequired[List[str]]
    temperature: NotRequired[float]
    tokens_used: NotRequired[float]


class GenaiPrompt(BaseModel):
    max_tokens: Optional[float] = None

    mcp_deferred_tools: Optional[List[str]] = None

    mcp_url: Optional[str] = None

    messages: Optional[List[GenaiContent]] = None

    model_id: Optional[str] = None

    raw: Optional[Dict[str, Any]] = None

    responses: Optional[List[str]] = None

    temperature: Optional[float] = None

    tokens_used: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "max_tokens",
                "mcp_deferred_tools",
                "mcp_url",
                "messages",
                "model_id",
                "raw",
                "responses",
                "temperature",
                "tokens_used",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
