"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lmscontentshapelocalization import (
    LmsContentShapeLocalization,
    LmsContentShapeLocalizationTypedDict,
)
from .lmsmedia import LmsMedia, LmsMediaTypedDict
from datetime import datetime
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict
from unified_python_sdk.types import BaseModel, UNSET_SENTINEL


class LmsContentTypedDict(TypedDict):
    categories: NotRequired[List[str]]
    collection_ids: NotRequired[List[str]]
    course_ids: NotRequired[List[str]]
    created_at: NotRequired[datetime]
    description: NotRequired[str]
    duration_minutes: NotRequired[float]
    external_reference: NotRequired[str]
    id: NotRequired[str]
    instructor_ids: NotRequired[List[str]]
    is_active: NotRequired[bool]
    languages: NotRequired[List[str]]
    localizations: NotRequired[List[LmsContentShapeLocalizationTypedDict]]
    media: NotRequired[List[LmsMediaTypedDict]]
    name: NotRequired[str]
    provider_name: NotRequired[str]
    raw: NotRequired[Dict[str, Any]]
    short_description: NotRequired[str]
    skills: NotRequired[List[str]]
    sort_order: NotRequired[float]
    updated_at: NotRequired[datetime]


class LmsContent(BaseModel):
    categories: Optional[List[str]] = None

    collection_ids: Optional[List[str]] = None

    course_ids: Optional[List[str]] = None

    created_at: Optional[datetime] = None

    description: Optional[str] = None

    duration_minutes: Optional[float] = None

    external_reference: Optional[str] = None

    id: Optional[str] = None

    instructor_ids: Optional[List[str]] = None

    is_active: Optional[bool] = None

    languages: Optional[List[str]] = None

    localizations: Optional[List[LmsContentShapeLocalization]] = None

    media: Optional[List[LmsMedia]] = None

    name: Optional[str] = None

    provider_name: Optional[str] = None

    raw: Optional[Dict[str, Any]] = None

    short_description: Optional[str] = None

    skills: Optional[List[str]] = None

    sort_order: Optional[float] = None

    updated_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "categories",
                "collection_ids",
                "course_ids",
                "created_at",
                "description",
                "duration_minutes",
                "external_reference",
                "id",
                "instructor_ids",
                "is_active",
                "languages",
                "localizations",
                "media",
                "name",
                "provider_name",
                "raw",
                "short_description",
                "skills",
                "sort_order",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
