"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict
from unified_python_sdk.types import BaseModel


class MetadataMetadataTypedDict(TypedDict):
    name: str
    object_type: str
    created_at: NotRequired[datetime]
    id: NotRequired[str]
    objects: NotRequired[Dict[str, str]]
    raw: NotRequired[Dict[str, Any]]
    type: NotRequired[str]
    updated_at: NotRequired[datetime]


class MetadataMetadata(BaseModel):
    name: str

    object_type: str

    created_at: Optional[datetime] = None

    id: Optional[str] = None

    objects: Optional[Dict[str, str]] = None

    raw: Optional[Dict[str, Any]] = None

    type: Optional[str] = None

    updated_at: Optional[datetime] = None
