"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unified_python_sdk.types import BaseModel, UNSET_SENTINEL


class PropertyCrmEventPageViewTypedDict(TypedDict):
    average: NotRequired[float]
    count: NotRequired[float]
    url: NotRequired[str]


class PropertyCrmEventPageView(BaseModel):
    average: Optional[float] = None

    count: Optional[float] = None

    url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["average", "count", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
