"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taskchangeitem import TaskChangeItem, TaskChangeItemTypedDict
from datetime import datetime
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict
from unified_python_sdk.types import BaseModel


class TaskChangeTypedDict(TypedDict):
    created_at: NotRequired[datetime]
    id: NotRequired[str]
    items: NotRequired[List[TaskChangeItemTypedDict]]
    raw: NotRequired[Dict[str, Any]]
    task_id: NotRequired[str]
    updated_at: NotRequired[datetime]
    user_id: NotRequired[str]


class TaskChange(BaseModel):
    created_at: Optional[datetime] = None

    id: Optional[str] = None

    items: Optional[List[TaskChangeItem]] = None

    raw: Optional[Dict[str, Any]] = None

    task_id: Optional[str] = None

    updated_at: Optional[datetime] = None

    user_id: Optional[str] = None
